/**
 * Toolkit-side helper for the Phase 1.4.6 `media-upload` edge
 * function on fgn.academy. POSTs base64-encoded image bytes; gets
 * back a public URL on the `media-assets` Supabase Storage bucket.
 *
 * Auth: X-App-Key header with the same key already provisioned for
 * scorm-publish (FGN_ACADEMY_APP_KEY env var).
 *
 * Used by enhance.ts when --upload-to-academy is set on the
 * `coverImage` slot — the AI-generated bytes get uploaded after
 * generation, and the manifest's `coverImageRemoteUrl` is stamped
 * with the returned URL.
 *
 * Note: this only fires for the AI-override regeneration path. The
 * default passthrough path (Phase 1.4.5.1) keeps the original
 * play.fgn.gg `cover_image_url` as `coverImageRemoteUrl` — no
 * re-upload needed since those bytes are already on Supabase Storage
 * (just on the play.fgn.gg project rather than fgn.academy's).
 */

const DEFAULT_ENDPOINT =
  'https://vfzjfkcwromssjnlrhoo.supabase.co/functions/v1';

export interface UploadCoverOptions {
  /**
   * fgn.academy app key. Defaults to FGN_ACADEMY_APP_KEY env var.
   * Same key already provisioned for `scorm-publish`.
   */
  appKey?: string;
  /**
   * Endpoint base URL. Defaults to fgn.academy production. Override
   * for local edge-function development against `supabase functions
   * serve`.
   */
  endpoint?: string;
  /**
   * Course ID — used in the storage path so multiple covers under
   * the same course are easy to spot in admin UI listings.
   */
  courseId: string;
}

export interface UploadCoverResult {
  /** Public URL to the uploaded image on fgn.academy media-assets. */
  url: string;
  /** Path within the `media-assets` bucket. */
  storagePath: string;
  /** Decoded byte count (echoed from the server). */
  bytes: number;
  /** Mime type (echoed from the server). */
  mimeType: string;
}

export class AcademyUploadError extends Error {
  constructor(
    message: string,
    public status: number,
    public body: unknown,
  ) {
    super(message);
    this.name = 'AcademyUploadError';
  }
}

/**
 * Upload cover image bytes to fgn.academy's media library.
 *
 * Throws AcademyUploadError on transport failure or non-200 response.
 * Caller (enhance.ts) catches the throw and turns it into a non-fatal
 * CourseWarning — the local cover.png is still bundled in the SCORM
 * ZIP regardless, so an upload failure doesn't break the course.
 */
export async function uploadCoverToAcademy(
  bytes: Buffer,
  mimeType: 'image/png' | 'image/jpeg' | 'image/webp',
  opts: UploadCoverOptions,
): Promise<UploadCoverResult> {
  const appKey = opts.appKey ?? process.env.FGN_ACADEMY_APP_KEY;
  if (!appKey) {
    throw new AcademyUploadError(
      'FGN_ACADEMY_APP_KEY required (env var or opts.appKey)',
      0,
      null,
    );
  }
  const endpoint = opts.endpoint ?? DEFAULT_ENDPOINT;

  // Pick a sane filename hint. The edge function uses the sha256
  // of the bytes for its actual storage path, so this is purely a
  // human-readable hint used in the request log.
  const ext =
    mimeType === 'image/png' ? 'png' : mimeType === 'image/webp' ? 'webp' : 'jpg';
  const filename = `cover.${ext}`;

  const res = await fetch(`${endpoint}/media-upload`, {
    method: 'POST',
    headers: {
      'X-App-Key': appKey,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      courseId: opts.courseId,
      slot: 'cover-image',
      filename,
      mimeType,
      bytes: bytes.toString('base64'),
    }),
  });

  if (!res.ok) {
    let errBody: unknown = await res.text();
    try {
      errBody = JSON.parse(errBody as string);
    } catch {
      // leave as raw text if not JSON
    }
    throw new AcademyUploadError(
      `media-upload returned HTTP ${res.status}`,
      res.status,
      errBody,
    );
  }

  const json = (await res.json()) as UploadCoverResult;
  return json;
}
