-- ===================================================================
-- 20260504120000_scorm_courses_table.sql
-- Phase 2 v0 — scorm_courses table for native SCORM hosting
-- ===================================================================
--
-- Purpose:
--   Stores SCORM courses generated by the Course Builder admin UI
--   on fgn.academy. Each row is a single (Work Order, destination)
--   variant — same Work Order can have up to 4 SCORM courses, one
--   per destination enum, each independently regenerable.
--
-- Consumed by:
--   1. Course Builder admin page (read/write all rows for the user's
--      tenant)
--   2. Work Order detail page (read published rows for the WO,
--      render as Learning Resource cards alongside sim_resources)
--   3. SCORM Player route at /scorm-player/:courseId/launch
--      (read row, fetch manifest_url, render player iframe)
--
-- Spec reference:
--   docs/PHASE_2_SPEC.md — "Database changes" section. See that doc
--   for the rationale on why this is a new table rather than an
--   extension of the existing courses/modules/lessons system.
--
-- Existing tables this migration depends on:
--   public.work_orders         (FK on work_order_id)
--   public.user_roles          (RLS check for admin role)
--   auth.users                 (FK on generated_by)
--
-- Idempotent? No. Run once. Re-runs will fail on the create table
-- statement.
-- ===================================================================


-- Note on helpers: this migration uses two existing helpers from
-- stratify-workforce that are dominant patterns in the codebase:
--   - update_updated_at_column()   for the updated_at trigger
--   - has_role(auth.uid(), '<role>') for RLS admin checks
-- We do NOT redeclare them here. If this migration is ever ported
-- to a project that lacks them, define them inline first.


-- ===================================================================
-- scorm_courses — primary table
-- ===================================================================
create table public.scorm_courses (
  id uuid primary key default gen_random_uuid(),

  -- Source Work Order (required, FK with cascade — deleting a Work
  -- Order also deletes any SCORM courses derived from it; admins
  -- shouldn't normally delete WOs, but if they do, orphan SCORMs
  -- are a footgun we don't want).
  work_order_id uuid not null references public.work_orders(id) on delete cascade,

  -- Destination determines distribution path. UNIQUE (work_order_id,
  -- destination) enforces the spec's multiplicity rule (one SCORM
  -- per Work Order per destination).
  destination text not null check (destination in (
    'fgn-academy',
    'broadband-workforce',
    'simu-cdl-path',
    'external-lms'
  )),

  -- Display metadata — drives the Learning Resource card on the
  -- Work Order page. cover_image_url is typically a public URL on
  -- media-assets/scorm-covers/... but can be any URL the toolkit
  -- stamped on CourseManifest.coverImageUrl during build.
  title text not null,
  description text,
  cover_image_url text,

  -- SCORM build artifacts. manifest_url is the public URL to the
  -- unzipped course.json under media-assets/scorm-courses/<id>/.
  -- zip_url is the full ZIP for external download. bundle_id
  -- corresponds to CourseManifest.id at the toolkit level.
  scorm_version text not null default '1.2'
    check (scorm_version in ('1.2', 'cmi5')),
  manifest_url text not null,
  zip_url text,
  bundle_id text not null,

  -- Publish state. Only is_published=true rows render as Learning
  -- Resource cards on Work Order pages. v0 default is true (admins
  -- usually want immediate publish); admins can flip to false for
  -- staging via the admin UI.
  is_published boolean not null default true,
  published_at timestamptz default now(),

  -- Build provenance for debugging, audit, future regenerate UX.
  -- generated_by is the admin who triggered the build.
  -- source_challenge_id is the play.fgn.gg challenge id; not
  -- enforceable as an FK because that table lives on a different
  -- Supabase project.
  -- ai_enhanced mirrors CourseManifest.aiEnhanced shape — { model,
  -- enhancedAt, inputHash, enhancedFields }.
  generated_by uuid references auth.users(id) on delete set null,
  source_challenge_id uuid,
  ai_enhanced jsonb,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- One SCORM course per (Work Order, destination). Regenerate
  -- replaces this row in place; admin UI shows a confirmation modal
  -- before overwriting.
  unique (work_order_id, destination)
);

create index scorm_courses_work_order_idx
  on public.scorm_courses(work_order_id);

create index scorm_courses_published_idx
  on public.scorm_courses(is_published)
  where is_published;

-- updated_at trigger — uses the existing update_updated_at_column()
-- helper (the dominant pattern in stratify-workforce).
create trigger scorm_courses_updated_at
before update on public.scorm_courses
for each row execute function public.update_updated_at_column();


-- ===================================================================
-- RLS — three policies
-- ===================================================================
alter table public.scorm_courses enable row level security;

-- 1. Anonymous + authenticated readers see published courses only.
--    This is what powers the Learning Resource card on the public
--    Work Order page (no login required to see the card on a
--    publicly-readable Work Order).
create policy "anyone can read published scorm courses"
on public.scorm_courses
for select
to public
using (is_published = true);

-- 2. Admins see ALL courses, published or not. Lets the Course
--    Builder UI show drafts in the existing-variants panel. Uses the
--    has_role() helper that's the dominant convention in
--    stratify-workforce (see RoleEscalationControls.tsx and dozens
--    of existing RLS policies on ai_model_configs, authorized_apps,
--    system_audit_logs, etc.).
create policy "admins can read all scorm courses"
on public.scorm_courses
for select
to authenticated
using (
  has_role(auth.uid(), 'admin')
  or has_role(auth.uid(), 'super_admin')
);

-- 3. Admins can insert/update/delete. Used by the scorm-build edge
--    function (which authenticates as the calling admin, NOT as
--    service role for the row-level operation — this matters for
--    `generated_by` to land correctly via auth.uid()).
--    Note: scorm-build uses service-role for storage operations
--    (writing artifacts) but the DB upsert goes through the user's
--    JWT so RLS applies.
create policy "admins can manage scorm courses"
on public.scorm_courses
for all
to authenticated
using (
  has_role(auth.uid(), 'admin')
  or has_role(auth.uid(), 'super_admin')
)
with check (
  has_role(auth.uid(), 'admin')
  or has_role(auth.uid(), 'super_admin')
);


-- ===================================================================
-- Documentation comments
-- ===================================================================
comment on table public.scorm_courses is
  'SCORM 1.2 courses generated by the Course Builder admin UI from fgn.academy Work Orders. One row per (Work Order, destination); regenerate replaces in place. See docs/PHASE_2_SPEC.md in the FGN SCORM toolkit repo for the full design.';

comment on column public.scorm_courses.destination is
  'Distribution path: fgn-academy renders as a Learning Resource card on the source Work Order page; the other three are admin-downloads-ZIP destinations.';

comment on column public.scorm_courses.manifest_url is
  'Public URL to the unzipped course.json under media-assets/scorm-courses/<id>/. The /scorm-player/:courseId/launch route fetches this and runs the player.';

comment on column public.scorm_courses.zip_url is
  'Public URL to the full SCORM ZIP under media-assets/scorm-bundles/<id>.zip. May be null for fgn-academy destination if admin only wants native rendering.';

comment on column public.scorm_courses.ai_enhanced is
  'Mirror of CourseManifest.aiEnhanced when AI slots ran during build. JSON shape: { model, enhancedAt, inputHash, enhancedFields }. Null when course was built from passthrough only.';
